spring.application.name=demo_database
# Database Connection settings 

### H2 settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console




### Postgres Settings
# spring.datasource.url=jdbc:postgresql://localhost:5432/ibm_training
# spring.datasource.username=postgres
# spring.datasource.password=7890
# spring.datasource.driver-class-name=org.postgresql.Driver

# # 2. JPA & Hibernate Behavior
# # 'update' automatically updates table structures based on your entity classes without deleting data.
# spring.jpa.hibernate.ddl-auto=update

# # Uses PostgreSQL specific SQL optimization dialects
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# # 3. Debugging (Optional)
# # Prints generated SQL statements to the VS Code terminal console
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true
